/* ============================================================
   Iguaçu Seguro — DADOS
   Animais, grupos e perguntas do quiz em constantes tipo JSON.
   TODO(evolução): migrar para animais.json consumido via fetch(),
   permitindo atualizar as espécies sem editar o código.
   ============================================================ */

const ANIMAIS = [
  {nome:"Jararaca", cientifico:"Bothrops jararaca", grupo:"cobras", icone:"🐍",
   desc:"Marrom com rajas pretas, faixa marrom atrás do olho, língua preta e íris dourada/verde.",
   sintomas:["Dor imediata, inchaço e calor no local","Manchas roxas e sangramento","Vômito, náusea e suor","Hipotensão, choque, bolhas e necrose","Insuficiência renal aguda","Picadas de filhotes podem não doer"],
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Jararacuçu", cientifico:"Bothrops jararacussu", grupo:"cobras", icone:"🐍",
   desc:"Fêmeas maiores e amareladas, machos cinza. Camuflagem quase perfeita; o bote alcança a distância do próprio corpo.",
   sintomas:["Mesmos do grupo Bothrops (jararaca/urutu)"],
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Urutu-cruzeiro", cientifico:"Bothrops alternatus", grupo:"cobras", icone:"🐍",
   desc:"Uma das cobras mais venenosas do Brasil. Agressiva quando ameaçada e muito rápida; desenho de cruz na cabeça.",
   sintomas:["Idem grupo Bothrops: dor, inchaço, sangramento, necrose e risco renal"],
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Cascavel", cientifico:"Crotalus durissus terrificus", grupo:"cobras", icone:"🐍",
   desc:"Reconhecida pelo guizo/chocalho na cauda — cada anel é uma troca de pele, não um ano de vida.",
   sintomas:["Dor ausente ou leve, inchaço discreto","Paralisia muscular e queda da pálpebra","Boca seca, visão turva ou dupla","Hemorragias discretas nas gengivas","Dor muscular e urina marrom/vermelha","Insuficiência renal aguda"],
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Coral", cientifico:"Micrurus sp", grupo:"cobras", icone:"🐍",
   desc:"Anéis pretos, brancos, vermelhos e amarelos. Difícil diferenciar das falsas — nunca se aproxime.",
   sintomas:["Podem ser tardios: dor discreta ou ausente","Formigamento e fraqueza muscular progressiva","Queda da pálpebra e salivação excessiva","Paralisia dos músculos do olho","Dificuldade de deglutir e respirar"],
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Cobra-verde / Cobra-cipó", cientifico:"Philodryas sp", grupo:"cobras", icone:"🌿",
   desc:"Vive em árvores; morde em vez de picar (dentes pequenos no fundo da boca).",
   sintomas:["Queimação, dor e sangramento local","Coceira e manchas vermelhas"],
   onde:"Serviço de saúde mais próximo"},
  {nome:"Caninana", cientifico:"Spilotes pullatus", grupo:"cobras", icone:"🌿", naoPeconhenta:true,
   desc:"Cobra rápida, mas NÃO peçonhenta. Geralmente mansa, foge quando avistada.",
   sintomas:["Não é perigosa — deixe-a seguir caminho"],
   onde:"—"},
  {nome:"Muçurana", cientifico:"Clelia sp", grupo:"cobras", icone:"🌿", naoPeconhenta:true,
   desc:"Cobra-preta que se alimenta de outras cobras (jararacas, urutus, cascavéis). Não peçonhenta.",
   sintomas:["Não é perigosa — aliada no controle de cobras venenosas"],
   onde:"—"},
  {nome:"Aranha-marrom", cientifico:"Loxosceles sp", grupo:"aranhas", icone:"🕷️",
   desc:"Pouco agressiva; pica em defesa (roupas, sapatos, enxadas, pás).",
   sintomas:["Picada quase imperceptível no início","Dor, inchaço enrijecido e vermelhidão","Bolha em 24–72h; necrose/escara em 7–12 dias","Febre, dor de cabeça e náuseas","Casos graves podem levar a coma"],
   onde:"UPA — Unidade de Pronto Atendimento"},
  {nome:"Aranha-armadeira", cientifico:"Phoneutria sp", grupo:"aranhas", icone:"🕷️",
   desc:"Muito agressiva, hábitos noturnos; mais acidentes em abril e maio. Vive em bananeiras, folhagens, madeira e dentro de casas. Ataca com as patas dianteiras erguidas.",
   sintomas:["Dor imediata que pode irradiar","Inchaço, queimação e suor","Marcas de dois pontos no local","Ereção peniana dolorosa (casos raros)","Choque e edema pulmonar"],
   onde:"UPA — Unidade de Pronto Atendimento"},
  {nome:"Aranha-de-jardim", cientifico:"Lycosa sp", grupo:"aranhas", icone:"🕷️",
   desc:"Não constrói teia; vive em gramados e jardins.",
   sintomas:["Acidentes não graves: dor local leve em menos de 20% dos casos"],
   onde:"Serviço de saúde mais próximo"},
  {nome:"Caranguejeira", cientifico:"Mygalomorphae", grupo:"aranhas", icone:"🕷️",
   desc:"Pernas longas com duas garras e corpo com cerdas.",
   sintomas:["Acidentes não graves","Irritação por pelos urticantes"],
   onde:"Serviço de saúde mais próximo"},
  {nome:"Escorpião-amarelo", cientifico:"Tityus serrulatus", grupo:"escorpioes", icone:"🦂",
   desc:"Pouco agressivo, hábitos noturnos; vive em pilhas de madeira, entulho, sob pedras e dentro de casas. O mais perigoso do grupo.",
   sintomas:["Dor local em ardor/queimação e coceira","Em casos moderados/graves (sobretudo crianças): febre ou corpo gelado, suor, náuseas, vômitos","Salivação, arritmias, falta de ar e agitação"],
   onde:"UPA — Unidade de Pronto Atendimento"},
  {nome:"Escorpião-marrom", cientifico:"Tityus bahiensis", grupo:"escorpioes", icone:"🦂",
   desc:"Noturno; encontrado em pilhas de madeira, cercas, entulho e sob pedras.",
   sintomas:["Dor local em ardor/queimação","Sintomas sistêmicos menos frequentes que no amarelo"],
   onde:"UPA — Unidade de Pronto Atendimento"},
  {nome:"Escorpião-preto", cientifico:"Bothriurus bonariensis", grupo:"escorpioes", icone:"🦂",
   desc:"Hábitos noturnos; vive sob pedras e troncos podres, próximo a construções.",
   sintomas:["Veneno de baixa toxicidade: dor local e hipersensibilidade"],
   onde:"Serviço de saúde mais próximo"},
  {nome:"Lagarta Lonomia", cientifico:"Lonomia obliqua", grupo:"outros", icone:"🐛",
   desc:"Lagarta venenosa que vira mariposa; cerdas espinhudas com veneno. Mais frequente de novembro a abril, em troncos de árvores, em grupos camuflados.",
   sintomas:["Dor em queimação, vermelhidão e inchaço","Mal-estar, dor de cabeça, náuseas e dor muscular","Hemorragias entre 8 e 72h (manchas escuras, sangramento por nariz, gengivas e urina)","Casos graves: insuficiência renal e morte"],
   tratamento:"Levar IMEDIATAMENTE ao hospital. Lavar com água fria e elevar o membro.",
   onde:"Hospital Municipal de Foz do Iguaçu (24h)"},
  {nome:"Lagartas urticantes", cientifico:"Megalopyge sp", grupo:"outros", icone:"🐛",
   desc:"De 1 a 8 cm, com \"pelos\" dorsais longos e sedosos que escondem cerdas urticantes.",
   sintomas:["Dor local intensa em queimação","Inchaço, vermelhidão e prurido","Raramente náuseas e vômito; dor some em ~1h"],
   tratamento:"Lavar com água fria, elevar o membro; medicação só com médico.",
   onde:"Serviço de saúde mais próximo"},
  {nome:"Sapo", cientifico:"Família Bufonidae", grupo:"outros", icone:"🐸",
   desc:"Tem glândulas de veneno atrás dos olhos, mas o veneno só é liberado se a glândula for comprimida. Urina de sapo NÃO cega — mito. Não jogue sal: eles respiram pela pele e o sal sufoca com dor.",
   sintomas:["Deixe-o em paz — defesa apenas contra predadores"],
   onde:"—"},
  {nome:"Vespas", cientifico:"Ordem Hymenoptera", grupo:"outros", icone:"🐝",
   desc:"Ferrão com veneno que causa reação local e, em alguns casos, alérgica.",
   sintomas:["Dor aguda, vermelhidão, prurido e edema","Possível reação alérgica, dor de cabeça e vertigem","Calafrios, agitação e opressão no peito"],
   tratamento:"Retirar o ferrão por raspagem (não pinçar); tratamento médico.",
   onde:"Serviço de saúde mais próximo"}
];

const GRUPOS = [
  {id:"todas", label:"Todas"}, {id:"cobras", label:"🐍 Cobras"},
  {id:"aranhas", label:"🕷️ Aranhas"}, {id:"escorpioes", label:"🦂 Escorpiões"},
  {id:"outros", label:"🐛 Outros"}
];

const QUIZ = [
  {p:"Ao presenciar uma picada de cobra, o primeiro passo é:",
   ops:["Matar a cobra e levá-la ao hospital","Afastar-se da cobra e manter a vítima deitada e calma","Dar um remédio para dor","Fazer um garrote"],
   c:1, exp:"Afastar-se evita a segunda picada; manter a vítima calma e imóvel retarda a circulação do veneno."},
  {p:"Fazer torniquete (garrote) na picada:",
   ops:["Ajuda a segurar o veneno","É o procedimento correto","NUNCA deve ser feito — piora o quadro","Só em casos graves"],
   c:2, exp:"O garrote concentra o veneno no membro e agrava a necrose. Nunca faça."},
  {p:"O tratamento eficaz para picada de cobra é:",
   ops:["Chupar o veneno","Soro antiofídico no hospital, gratuito pelo SUS","Pó de café na ferida","Remédio caseiro"],
   c:1, exp:"Somente o soro antiofídico, aplicado no hospital, neutraliza o veneno — e é gratuito pelo SUS."},
  {p:"Como reconhecer uma cascavel:",
   ops:["Pelo guizo/chocalho na cauda","Pelos anéis coloridos","Pela língua preta","Pelo desenho de cruz na cabeça"],
   c:0, exp:"O chocalho/guizo na cauda é a marca da cascavel. Anéis coloridos = coral; cruz na cabeça = urutu."},
  {p:"A lagarta Lonomia é encontrada geralmente:",
   ops:["Dentro de casas","Em troncos de árvores, em grupos camuflados","Na água","Em teias nos cantos"],
   c:1, exp:"Ela vive em troncos e é mais frequente entre novembro e abril."},
  {p:"\"Urina de sapo cega\" é:",
   ops:["Verdade","Mito — não há esse perigo","Depende da espécie","Só com sapos grandes"],
   c:1, exp:"É um mito popular. O veneno do sapo fica em glândulas atrás dos olhos e só sai se comprimido."}
];